export const AUTHORIZED = "AUTHORIZED";
export const ADD_ALBUM = "ADD_ALBUM";
export const ADD_ALBUMS_BATCH = "ADD_ALBUMS_BATCH";
export const REMOVE_ALBUMS_BATCH = "REMOVE_ALBUMS_BATCH";
export const ADD_PHOTOS_BATCH = "ADD_PHOTOS_BATCH";
export const MERGE_PHOTO_GROUPS = "SET_PHOTO_GROUP";